async function Module(moduleArg={}){var moduleRtn;var g=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,p=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer";if(p){let {createRequire:a}=await import("node:module");var require=a(import.meta.url)}var t=(a,b)=>{throw b;},u=import.meta.url,w="",x,y;
if(p){var fs=require("node:fs");u.startsWith("file:")&&(w=require("node:path").dirname(require("node:url").fileURLToPath(u))+"/");y=a=>{a=ca(a)?new URL(a):a;return fs.readFileSync(a)};x=async a=>{a=ca(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);t=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{w=(new URL(".",u)).href}catch{}x=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}console.log.bind(console);
var z=console.error.bind(console),C,D=!1,E,ca=a=>a.startsWith("file://"),da,ea,fa=!1;function ha(){var a=F.buffer;ia=new Int8Array(a);G=new Int16Array(a);H=new Uint8Array(a);K=new Uint16Array(a);L=new Int32Array(a);M=new Uint32Array(a);ja=new Float32Array(a);la=new Float64Array(a);ma=new BigInt64Array(a);na=new BigUint64Array(a)}function oa(a){g.onAbort?.(a);a=`Aborted(${a})`;z(a);D=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ea?.(a);throw a;}var pa;
async function qa(a){if(!C)try{var b=await x(a);return new Uint8Array(b)}catch{}if(a==pa&&C)a=new Uint8Array(C);else if(y)a=y(a);else throw"both async and sync fetching of the wasm failed";return a}async function ra(a,b){try{var c=await qa(a);return await WebAssembly.instantiate(c,b)}catch(d){z(`failed to asynchronously prepare wasm: ${d}`),oa(d)}}
async function sa(a){var b=pa;if(!C&&!p)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){z(`wasm streaming compile failed: ${d}`),z("falling back to ArrayBuffer instantiation")}return ra(b,a)}class ta{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var G,L,ma,ia,ja,la,K,M,na,H,ua=a=>{for(;a.length>0;)a.shift()(g)},va=[],wa=[],xa=()=>{var a=g.preRun.shift();wa.push(a)},N=!0;
class ya{constructor(a){this.K=a-24}init(a,b){M[this.K+16>>2]=0;M[this.K+4>>2]=a;M[this.K+8>>2]=b}}var za=0,O=a=>{for(var b="";;){var c=H[a++];if(!c)return b;b+=String.fromCharCode(c)}},P={},Q={},R={},S=class extends Error{constructor(a){super(a);this.name="BindingError"}},Aa=a=>{throw new S(a);};
function Ba(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(Q.hasOwnProperty(a)){if(c.N)return;throw new S(`Cannot register type '${d}' twice`);}Q[a]=b;delete R[a];P.hasOwnProperty(a)&&(b=P[a],delete P[a],b.forEach(e=>e()))}function T(a,b,c={}){return Ba(a,b,c)}
var Ca=(a,b,c)=>{switch(b){case 1:return c?d=>ia[d]:d=>H[d];case 2:return c?d=>G[d>>1]:d=>K[d>>1];case 4:return c?d=>L[d>>2]:d=>M[d>>2];case 8:return c?d=>ma[d>>3]:d=>na[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Da=[],U=[0,1,,1,null,1,!0,1,!1,1],Ea=a=>{a>9&&0===--U[a+1]&&(U[a]=void 0,Da.push(a))},V=a=>{if(!a)throw new S(`Cannot use deleted val. handle = ${a}`);return U[a]},W=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:let b=
Da.pop()||U.length;U[b]=a;U[b+1]=1;return b}};function Fa(a){return this.F(M[a>>2])}var Ga={name:"emscripten::val",F:a=>{var b=V(a);Ea(a);return b},I:(a,b)=>W(b),J:Fa,H:null},Ha=(a,b)=>{switch(b){case 4:return function(c){return this.F(ja[c>>2])};case 8:return function(c){return this.F(la[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Ia=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Ma(a){for(var b=1;b<a.length;++b)if(a[b]!==null&&a[b].H===void 0)return!0;return!1}
var Na=(a,b)=>{if(void 0===g[a].G){var c=g[a];g[a]=function(...d){if(!g[a].G.hasOwnProperty(d.length))throw new S(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${g[a].G})!`);return g[a].G[d.length].apply(this,d)};g[a].G=[];g[a].G[c.L]=c}},Oa=(a,b,c)=>{if(g.hasOwnProperty(a)){if(void 0===c||void 0!==g[a].G&&void 0!==g[a].G[c])throw new S(`Cannot register public name '${a}' twice`);Na(a,a);if(g[a].G.hasOwnProperty(c))throw new S(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
g[a].G[c]=b}else g[a]=b,g[a].L=c},Pa=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(M[b+d*4>>2]);return c},Qa=class extends Error{constructor(a){super(a);this.name="InternalError"}},Sa=(a,b)=>{a=O(a);var c=Ra.get(b);if(typeof c!="function")throw new S(`unknown function pointer with signature ${a}: ${b}`);return c};class Ta extends Error{}
var Va=a=>{a=Ua(a);var b=O(a);X(a);return b},Wa=(a,b)=>{function c(f){e[f]||Q[f]||(R[f]?R[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Ta(`${a}: `+d.map(Va).join([", "]));},Xa=(a,b)=>{function c(h){h=b(h);if(h.length!==d.length)throw new Qa("Mismatched type converter count");for(var m=0;m<d.length;++m)T(d[m],h[m])}var d=[];d.forEach(h=>R[h]=a);var e=Array(a.length),f=[],k=0;for(let [h,m]of a.entries())Q.hasOwnProperty(m)?e[h]=Q[m]:(f.push(m),P.hasOwnProperty(m)||(P[m]=[]),
P[m].push(()=>{e[h]=Q[m];++k;k===f.length&&c(e)}));0===f.length&&c(e)},Ya=a=>{a=a.trim();var b=a.indexOf("(");return b===-1?a:a.slice(0,b)},Za=new TextDecoder,$a=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},ab=new TextDecoder("utf-16le"),bb=(a,b,c)=>{a>>=1;return ab.decode(K.subarray(a,$a(K,a,b/2,c)))},cb=(a,b,c)=>{c??=2147483647;if(c<2)return 0;c-=2;var d=b;c=c<a.length*2?c/2:a.length;for(var e=0;e<c;++e)G[b>>1]=a.charCodeAt(e),b+=2;G[b>>1]=0;return b-d},db=a=>a.length*2,eb=
(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=M[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},fb=(a,b,c)=>{c??=2147483647;if(c<4)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);f>65535&&e++;L[b>>2]=f;b+=4;if(b+4>c)break}L[b>>2]=0;return b-d},gb=a=>{for(var b=0,c=0;c<a.length;++c)a.codePointAt(c)>65535&&c++,b+=4;return b},hb=0,ib=[],jb=a=>{var b=ib.length;ib.push(a);return b},kb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=M[b+d*4>>2],k=Q[f];
if(void 0===k)throw a=`${`parameter ${d}`} has unknown type ${Va(f)}`,new S(a);c[e]=k}return c},lb=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(M[b>>2]=W(d));return a},mb={},nb=a=>{var b=mb[a];return b===void 0?O(a):b},Y={},ob=a=>{E=a;N||hb>0||(g.onExit?.(a),D=!0);t(a,new ta(a))},pb=a=>{if(!D)try{a()}catch(b){b instanceof ta||b=="unwind"||t(1,b)}finally{if(!(N||hb>0))try{E=a=E,ob(a)}catch(b){b instanceof ta||b=="unwind"||t(1,b)}}};g.noExitRuntime&&(N=g.noExitRuntime);g.printErr&&(z=g.printErr);
g.wasmBinary&&(C=g.wasmBinary);if(g.preInit)for(typeof g.preInit=="function"&&(g.preInit=[g.preInit]);g.preInit.length>0;)g.preInit.shift()();
var qb,X,Ua,rb,F,Ra,sb={j:(a,b,c)=>{(new ya(a)).init(b,c);za++;oa()},r:()=>oa(""),h:(a,b,c,d,e)=>{b=O(b);d=d===0n;var f=k=>k;if(d){let k=c*8;f=h=>BigInt.asUintN(k,h);e=f(e)}T(a,{name:b,F:f,I:(k,h)=>{typeof h=="number"&&(h=BigInt(h));return h},J:Ca(b,c,!d),H:null})},u:(a,b,c,d)=>{b=O(b);T(a,{name:b,F:function(e){return!!e},I:function(e,f){return f?c:d},J:function(e){return this.F(H[e])},H:null})},s:a=>T(a,Ga),g:(a,b,c)=>{b=O(b);T(a,{name:b,F:d=>d,I:(d,e)=>e,J:Ha(b,c),H:null})},w:(a,b,c,d,e,f,k)=>{var h=
Pa(b,c);a=O(a);a=Ya(a);e=Sa(d,e);Oa(a,function(){Wa(`Cannot call ${a} due to unbound types`,h)},b-1);Xa(h,m=>{var l=[m[0],null].concat(m.slice(1));m=a;var A=a;var I=e,n=l.length;if(n<2)throw new S("argTypes array size mismatch! Must at least get return value and 'this' types!");var B=l[1]!==null&&!1,J=Ma(l),Ja=!l[0].M,q=l[0],v=l[1];I=[A,Aa,I,f,Ia,q.F.bind(q),v?.I.bind(v)];for(q=2;q<n;++q)v=l[q],I.push(v.I.bind(v));if(!J)for(q=B?1:2;q<l.length;++q)l[q].H!==null&&I.push(l[q].H);J=Ma(l);q=l.length-2;
var r=[];v=["fn"];B&&v.push("thisWired");for(n=0;n<q;++n)r.push(`arg${n}`),v.push(`arg${n}Wired`);r=r.join(",");v=v.join(",");r=`return function (${r}) {\n`;J&&(r+="var destructors = [];\n");var Ka=J?"destructors":"null",ka="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");B&&(r+=`var thisWired = toClassParamWire(${Ka}, this);\n`);for(n=0;n<q;++n){var La=`toArg${n}Wire`;r+=`var arg${n}Wired = ${La}(${Ka}, arg${n});\n`;ka.push(La)}r+=(Ja||k?"var rv = ":
"")+`invoker(${v});\n`;if(J)r+="runDestructors(destructors);\n";else for(n=B?1:2;n<l.length;++n)B=n===1?"thisWired":"arg"+(n-2)+"Wired",l[n].H!==null&&(r+=`${B}_dtor(${B});\n`,ka.push(`${B}_dtor`));Ja&&(r+="var ret = fromRetWire(rv);\nreturn ret;\n");l=(new Function(ka,r+"}\n"))(...I);A=Object.defineProperty(l,"name",{value:A});l=b-1;if(!g.hasOwnProperty(m))throw new Qa("Replacing nonexistent public symbol");void 0!==g[m].G&&void 0!==l?g[m].G[l]=A:(g[m]=A,g[m].L=l);return[]})},b:(a,b,c,d,e)=>{b=O(b);
var f=h=>h;if(d===0){var k=32-8*c;f=h=>h<<k>>>k;e=f(e)}T(a,{name:b,F:f,I:(h,m)=>m,J:Ca(b,c,d!==0),H:null})},a:(a,b,c)=>{function d(f){return new e(ia.buffer,M[f+4>>2],M[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=O(c);T(a,{name:c,F:d,J:d},{N:!0})},t:(a,b)=>{b=O(b);T(a,{name:b,F(c){var d=(d=c+4)?Za.decode(H.subarray(d,$a(H,d,M[c>>2],!0))):"";X(c);return d},I(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));
var e,f=typeof d=="string";if(!(f||ArrayBuffer.isView(d)&&d.BYTES_PER_ELEMENT==1))throw new S("Cannot pass non-string to std::string");var k;if(f)for(e=k=0;e<d.length;++e){var h=d.charCodeAt(e);h<=127?k++:h<=2047?k+=2:h>=55296&&h<=57343?(k+=4,++e):k+=3}else k=d.length;e=k;k=qb(4+e+1);h=k+4;M[k>>2]=e;if(f){if(f=h,h=e+1,e=H,h>0){h=f+h-1;for(var m=0;m<d.length;++m){var l=d.codePointAt(m);if(l<=127){if(f>=h)break;e[f++]=l}else if(l<=2047){if(f+1>=h)break;e[f++]=192|l>>6;e[f++]=128|l&63}else if(l<=65535){if(f+
2>=h)break;e[f++]=224|l>>12;e[f++]=128|l>>6&63;e[f++]=128|l&63}else{if(f+3>=h)break;e[f++]=240|l>>18;e[f++]=128|l>>12&63;e[f++]=128|l>>6&63;e[f++]=128|l&63;m++}}e[f]=0}}else H.set(d,h);c!==null&&c.push(X,k);return k},J:Fa,H(c){X(c)}})},e:(a,b,c)=>{c=O(c);if(b===2){var d=bb;var e=cb;var f=db}else d=eb,e=fb,f=gb;T(a,{name:c,F:k=>{var h=d(k+4,M[k>>2]*b,!0);X(k);return h},I:(k,h)=>{if(typeof h!="string")throw new S(`Cannot pass non-string to C++ string type ${c}`);var m=f(h),l=qb(4+m+b);M[l>>2]=m/b;e(h,
l+4,m+b);k!==null&&k.push(X,l);return l},J:Fa,H(k){X(k)}})},i:(a,b)=>{b=O(b);T(a,{M:!0,name:b,F:()=>{},I:()=>{}})},q:()=>{N=!1;hb=0},d:(a,b,c)=>{var d;[b,...d]=kb(a,b);var e=b.I.bind(b),f=d.map(m=>m.J.bind(m));a--;var k={toValue:V};a=f.map((m,l)=>{var A=`argFromPtr${l}`;k[A]=m;return`${A}(args${l?"+"+l*8:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:k.getStringOrSymbol=nb,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=
`(${a})`;b.M||(k.toReturnWire=e,k.emval_returnValue=lb,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n${h}\n}`;c=(new Function(Object.keys(k),h))(...Object.values(k));b=`methodCaller<(${d.map(m=>m.name)}) => ${b.name}>`;return jb(Object.defineProperty(c,"name",{value:b}))},v:Ea,f:(a,b)=>{a=V(a);b=V(b);return W(a[b])},l:a=>{a>9&&(U[a+1]+=1)},c:(a,b,c,d,e)=>ib[a](b,c,d,e),m:a=>W(nb(a)),k:a=>{var b=V(a);Ia(b);Ea(a)},
n:(a,b)=>{Y[a]&&(clearTimeout(Y[a].id),delete Y[a]);if(!b)return 0;var c=setTimeout(()=>{delete Y[a];pb(()=>rb(a,performance.now()))},b);Y[a]={id:c,O:b};return 0},o:a=>{var b=H.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-F.buffer.byteLength+65535)/65536|0;try{F.grow(d);ha();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},p:ob},Z;
Z=await (async function(){function a(c){c=Z=c.exports;qb=c.z;X=c.A;Ua=c.B;rb=c.D;F=c.x;Ra=c.C;ha();return Z}var b={a:sb};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,e))})});pa??=g.locateFile?g.locateFile?g.locateFile("image_core_module.wasm",w):w+"image_core_module.wasm":(new URL("image_core_module.wasm",import.meta.url)).href;return function(c){return a(c.instance)}(await sa(b))}());
(function(){function a(){g.calledRun=!0;if(!D){fa=!0;Z.y();da?.(g);g.onRuntimeInitialized?.();if(g.postRun)for(typeof g.postRun=="function"&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();va.push(b)}ua(va)}}if(g.preRun)for(typeof g.preRun=="function"&&(g.preRun=[g.preRun]);g.preRun.length;)xa();ua(wa);g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);a()},1)):a()})();fa?moduleRtn=g:moduleRtn=new Promise((a,b)=>{da=a;ea=b});
;return moduleRtn}export default Module;
