async function Module(moduleArg={}){var moduleRtn;var g=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,p=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer";if(p){let {createRequire:a}=await import("node:module");var require=a(import.meta.url)}var t=(a,b)=>{throw b;},u=import.meta.url,w="",ca,x;
if(p){var fs=require("node:fs");u.startsWith("file:")&&(w=require("node:path").dirname(require("node:url").fileURLToPath(u))+"/");x=a=>{a=da(a)?new URL(a):a;return fs.readFileSync(a)};ca=async a=>{a=da(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);t=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{w=(new URL(".",u)).href}catch{}ba&&(x=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ca=async a=>
{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}console.log.bind(console);var y=console.error.bind(console),z,A=!1,ea,da=a=>a.startsWith("file://"),fa,ha,ia=!1;function ja(){var a=D.buffer;ka=new Int8Array(a);E=new Int16Array(a);F=new Uint8Array(a);G=new Uint16Array(a);H=new Int32Array(a);I=new Uint32Array(a);ma=new Float32Array(a);na=new Float64Array(a);oa=new BigInt64Array(a);pa=new BigUint64Array(a)}
function L(a){g.onAbort?.(a);a=`Aborted(${a})`;y(a);A=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ha?.(a);throw a;}var qa;async function ra(a){if(!z)try{var b=await ca(a);return new Uint8Array(b)}catch{}if(a==qa&&z)a=new Uint8Array(z);else if(x)a=x(a);else throw"both async and sync fetching of the wasm failed";return a}
async function sa(a,b){try{var c=await ra(a);return await WebAssembly.instantiate(c,b)}catch(d){y(`failed to asynchronously prepare wasm: ${d}`),L(d)}}async function ta(a){var b=qa;if(!z&&!p)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){y(`wasm streaming compile failed: ${d}`),y("falling back to ArrayBuffer instantiation")}return sa(b,a)}
class ua{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var E,H,oa,ka,ma,na,G,I,pa,F,va=a=>{for(;a.length>0;)a.shift()(g)},wa=[],xa=[],ya=()=>{var a=g.preRun.shift();xa.push(a)},M=!0,za=new TextDecoder,Aa=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},N=(a,b,c)=>a?za.decode(F.subarray(a,Aa(F,a,b,c))):"";class Ba{constructor(a){this.M=a-24}init(a,b){I[this.M+16>>2]=0;I[this.M+4>>2]=a;I[this.M+8>>2]=b}}
var Ca=0,O=a=>{for(var b="";;){var c=F[a++];if(!c)return b;b+=String.fromCharCode(c)}},P={},Q={},R={},S=class extends Error{constructor(a){super(a);this.name="BindingError"}},Da=a=>{throw new S(a);};function Ea(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(Q.hasOwnProperty(a)){if(c.P)return;throw new S(`Cannot register type '${d}' twice`);}Q[a]=b;delete R[a];P.hasOwnProperty(a)&&(b=P[a],delete P[a],b.forEach(e=>e()))}
function T(a,b,c={}){return Ea(a,b,c)}
var Fa=(a,b,c)=>{switch(b){case 1:return c?d=>ka[d]:d=>F[d];case 2:return c?d=>E[d>>1]:d=>G[d>>1];case 4:return c?d=>H[d>>2]:d=>I[d>>2];case 8:return c?d=>oa[d>>3]:d=>pa[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ga=[],U=[0,1,,1,null,1,!0,1,!1,1],Ha=a=>{a>9&&0===--U[a+1]&&(U[a]=void 0,Ga.push(a))},V=a=>{if(!a)throw new S(`Cannot use deleted val. handle = ${a}`);return U[a]},W=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:let b=
Ga.pop()||U.length;U[b]=a;U[b+1]=1;return b}};function Ia(a){return this.H(I[a>>2])}var Ja={name:"emscripten::val",H:a=>{var b=V(a);Ha(a);return b},K:(a,b)=>W(b),L:Ia,J:null},Ka=(a,b)=>{switch(b){case 4:return function(c){return this.H(ma[c>>2])};case 8:return function(c){return this.H(na[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Oa=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Pa(a){for(var b=1;b<a.length;++b)if(a[b]!==null&&a[b].J===void 0)return!0;return!1}
var Qa=(a,b)=>{if(void 0===g[a].I){var c=g[a];g[a]=function(...d){if(!g[a].I.hasOwnProperty(d.length))throw new S(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${g[a].I})!`);return g[a].I[d.length].apply(this,d)};g[a].I=[];g[a].I[c.N]=c}},Ra=(a,b,c)=>{if(g.hasOwnProperty(a)){if(void 0===c||void 0!==g[a].I&&void 0!==g[a].I[c])throw new S(`Cannot register public name '${a}' twice`);Qa(a,a);if(g[a].I.hasOwnProperty(c))throw new S(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
g[a].I[c]=b}else g[a]=b,g[a].N=c},Sa=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(I[b+d*4>>2]);return c},Ta=class extends Error{constructor(a){super(a);this.name="InternalError"}},Va=(a,b)=>{a=O(a);var c=Ua.get(b);if(typeof c!="function")throw new S(`unknown function pointer with signature ${a}: ${b}`);return c};class Wa extends Error{}
var Ya=a=>{a=Xa(a);var b=O(a);X(a);return b},Za=(a,b)=>{function c(f){e[f]||Q[f]||(R[f]?R[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Wa(`${a}: `+d.map(Ya).join([", "]));},$a=(a,b)=>{function c(h){h=b(h);if(h.length!==d.length)throw new Ta("Mismatched type converter count");for(var m=0;m<d.length;++m)T(d[m],h[m])}var d=[];d.forEach(h=>R[h]=a);var e=Array(a.length),f=[],k=0;for(let [h,m]of a.entries())Q.hasOwnProperty(m)?e[h]=Q[m]:(f.push(m),P.hasOwnProperty(m)||(P[m]=[]),
P[m].push(()=>{e[h]=Q[m];++k;k===f.length&&c(e)}));0===f.length&&c(e)},ab=a=>{a=a.trim();var b=a.indexOf("(");return b===-1?a:a.slice(0,b)},bb=new TextDecoder("utf-16le"),cb=(a,b,c)=>{a>>=1;return bb.decode(G.subarray(a,Aa(G,a,b/2,c)))},db=(a,b,c)=>{c??=2147483647;if(c<2)return 0;c-=2;var d=b;c=c<a.length*2?c/2:a.length;for(var e=0;e<c;++e)E[b>>1]=a.charCodeAt(e),b+=2;E[b>>1]=0;return b-d},eb=a=>a.length*2,fb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=I[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},
gb=(a,b,c)=>{c??=2147483647;if(c<4)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);f>65535&&e++;H[b>>2]=f;b+=4;if(b+4>c)break}H[b>>2]=0;return b-d},hb=a=>{for(var b=0,c=0;c<a.length;++c)a.codePointAt(c)>65535&&c++,b+=4;return b},ib=0,jb=[],kb=a=>{var b=jb.length;jb.push(a);return b},lb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=I[b+d*4>>2],k=Q[f];if(void 0===k)throw a=`${`parameter ${d}`} has unknown type ${Ya(f)}`,new S(a);c[e]=k}return c},mb=(a,b,c)=>{var d=[];
a=a(d,c);d.length&&(I[b>>2]=W(d));return a},nb={},ob=a=>{var b=nb[a];return b===void 0?O(a):b},Y={},pb=a=>{ea=a;M||ib>0||(g.onExit?.(a),A=!0);t(a,new ua(a))},qb=a=>{if(!A)try{a()}catch(b){b instanceof ua||b=="unwind"||t(1,b)}finally{if(!(M||ib>0))try{ea=a=ea,pb(a)}catch(b){b instanceof ua||b=="unwind"||t(1,b)}}};g.noExitRuntime&&(M=g.noExitRuntime);g.printErr&&(y=g.printErr);g.wasmBinary&&(z=g.wasmBinary);if(g.preInit)for(typeof g.preInit=="function"&&(g.preInit=[g.preInit]);g.preInit.length>0;)g.preInit.shift()();
var rb,X,Xa,sb,D,Ua,tb={a:(a,b,c,d)=>L(`Assertion failed: ${N(a)}, at: `+[b?N(b):"unknown filename",c,d?N(d):"unknown function"]),q:(a,b,c)=>{(new Ba(a)).init(b,c);Ca++;L()},v:()=>L(""),o:(a,b,c,d,e)=>{b=O(b);d=d===0n;var f=k=>k;if(d){let k=c*8;f=h=>BigInt.asUintN(k,h);e=f(e)}T(a,{name:b,H:f,K:(k,h)=>{typeof h=="number"&&(h=BigInt(h));return h},L:Fa(b,c,!d),J:null})},y:(a,b,c,d)=>{b=O(b);T(a,{name:b,H:function(e){return!!e},K:function(e,f){return f?c:d},L:function(e){return this.H(F[e])},J:null})},
w:a=>T(a,Ja),n:(a,b,c)=>{b=O(b);T(a,{name:b,H:d=>d,K:(d,e)=>e,L:Ka(b,c),J:null})},d:(a,b,c,d,e,f,k)=>{var h=Sa(b,c);a=O(a);a=ab(a);e=Va(d,e);Ra(a,function(){Za(`Cannot call ${a} due to unbound types`,h)},b-1);$a(h,m=>{var l=[m[0],null].concat(m.slice(1));m=a;var B=a;var J=e,n=l.length;if(n<2)throw new S("argTypes array size mismatch! Must at least get return value and 'this' types!");var C=l[1]!==null&&!1,K=Pa(l),La=!l[0].O,q=l[0],v=l[1];J=[B,Da,J,f,Oa,q.H.bind(q),v?.K.bind(v)];for(q=2;q<n;++q)v=
l[q],J.push(v.K.bind(v));if(!K)for(q=C?1:2;q<l.length;++q)l[q].J!==null&&J.push(l[q].J);K=Pa(l);q=l.length-2;var r=[];v=["fn"];C&&v.push("thisWired");for(n=0;n<q;++n)r.push(`arg${n}`),v.push(`arg${n}Wired`);r=r.join(",");v=v.join(",");r=`return function (${r}) {\n`;K&&(r+="var destructors = [];\n");var Ma=K?"destructors":"null",la="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");C&&(r+=`var thisWired = toClassParamWire(${Ma}, this);\n`);for(n=0;n<q;++n){var Na=
`toArg${n}Wire`;r+=`var arg${n}Wired = ${Na}(${Ma}, arg${n});\n`;la.push(Na)}r+=(La||k?"var rv = ":"")+`invoker(${v});\n`;if(K)r+="runDestructors(destructors);\n";else for(n=C?1:2;n<l.length;++n)C=n===1?"thisWired":"arg"+(n-2)+"Wired",l[n].J!==null&&(r+=`${C}_dtor(${C});\n`,la.push(`${C}_dtor`));La&&(r+="var ret = fromRetWire(rv);\nreturn ret;\n");l=(new Function(la,r+"}\n"))(...J);B=Object.defineProperty(l,"name",{value:B});l=b-1;if(!g.hasOwnProperty(m))throw new Ta("Replacing nonexistent public symbol");
void 0!==g[m].I&&void 0!==l?g[m].I[l]=B:(g[m]=B,g[m].N=l);return[]})},e:(a,b,c,d,e)=>{b=O(b);var f=h=>h;if(d===0){var k=32-8*c;f=h=>h<<k>>>k;e=f(e)}T(a,{name:b,H:f,K:(h,m)=>m,L:Fa(b,c,d!==0),J:null})},b:(a,b,c)=>{function d(f){return new e(ka.buffer,I[f+4>>2],I[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=O(c);T(a,{name:c,H:d,L:d},{P:!0})},x:(a,b)=>{b=O(b);T(a,{name:b,H(c){var d=N(c+4,I[c>>2],!0);X(c);
return d},K(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,f=typeof d=="string";if(!(f||ArrayBuffer.isView(d)&&d.BYTES_PER_ELEMENT==1))throw new S("Cannot pass non-string to std::string");var k;if(f)for(e=k=0;e<d.length;++e){var h=d.charCodeAt(e);h<=127?k++:h<=2047?k+=2:h>=55296&&h<=57343?(k+=4,++e):k+=3}else k=d.length;e=k;k=rb(4+e+1);h=k+4;I[k>>2]=e;if(f){if(f=h,h=e+1,e=F,h>0){h=f+h-1;for(var m=0;m<d.length;++m){var l=d.codePointAt(m);if(l<=127){if(f>=h)break;e[f++]=l}else if(l<=2047){if(f+
1>=h)break;e[f++]=192|l>>6;e[f++]=128|l&63}else if(l<=65535){if(f+2>=h)break;e[f++]=224|l>>12;e[f++]=128|l>>6&63;e[f++]=128|l&63}else{if(f+3>=h)break;e[f++]=240|l>>18;e[f++]=128|l>>12&63;e[f++]=128|l>>6&63;e[f++]=128|l&63;m++}}e[f]=0}}else F.set(d,h);c!==null&&c.push(X,k);return k},L:Ia,J(c){X(c)}})},k:(a,b,c)=>{c=O(c);if(b===2){var d=cb;var e=db;var f=eb}else d=fb,e=gb,f=hb;T(a,{name:c,H:k=>{var h=d(k+4,I[k>>2]*b,!0);X(k);return h},K:(k,h)=>{if(typeof h!="string")throw new S(`Cannot pass non-string to C++ string type ${c}`);
var m=f(h),l=rb(4+m+b);I[l>>2]=m/b;e(h,l+4,m+b);k!==null&&k.push(X,l);return l},L:Ia,J(k){X(k)}})},z:(a,b)=>{b=O(b);T(a,{O:!0,name:b,H:()=>{},K:()=>{}})},u:()=>{M=!1;ib=0},h:(a,b,c)=>{var d;[b,...d]=lb(a,b);var e=b.K.bind(b),f=d.map(m=>m.L.bind(m));a--;var k={toValue:V};a=f.map((m,l)=>{var B=`argFromPtr${l}`;k[B]=m;return`${B}(args${l?"+"+l*8:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:k.getStringOrSymbol=ob,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=
`(${a})`;b.O||(k.toReturnWire=e,k.emval_returnValue=mb,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n${h}\n}`;c=(new Function(Object.keys(k),h))(...Object.values(k));b=`methodCaller<(${d.map(m=>m.name)}) => ${b.name}>`;return kb(Object.defineProperty(c,"name",{value:b}))},c:Ha,p:(a,b)=>{a=V(a);b=V(b);return W(a[b])},i:a=>{a>9&&(U[a+1]+=1)},g:(a,b,c,d,e)=>jb[a](b,c,d,e),j:a=>W(ob(a)),m:()=>W({}),f:a=>{var b=V(a);Oa(b);
Ha(a)},l:(a,b,c)=>{a=V(a);b=V(b);c=V(c);a[b]=c},r:(a,b)=>{Y[a]&&(clearTimeout(Y[a].id),delete Y[a]);if(!b)return 0;var c=setTimeout(()=>{delete Y[a];qb(()=>sb(a,performance.now()))},b);Y[a]={id:c,R:b};return 0},s:a=>{var b=F.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-D.buffer.byteLength+65535)/65536|0;try{D.grow(d);ja();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},
t:pb},Z;Z=await (async function(){function a(c){c=Z=c.exports;rb=c.D;X=c.E;Xa=c.F;sb=c.G;D=c.A;Ua=c.C;ja();return Z}var b={a:tb};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,e))})});qa??=g.locateFile?g.locateFile?g.locateFile("image_core_module.wasm",w):w+"image_core_module.wasm":(new URL("image_core_module.wasm",import.meta.url)).href;return function(c){return a(c.instance)}(await ta(b))}());
(function(){function a(){g.calledRun=!0;if(!A){ia=!0;Z.B();fa?.(g);g.onRuntimeInitialized?.();if(g.postRun)for(typeof g.postRun=="function"&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();wa.push(b)}va(wa)}}if(g.preRun)for(typeof g.preRun=="function"&&(g.preRun=[g.preRun]);g.preRun.length;)ya();va(xa);g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);a()},1)):a()})();ia?moduleRtn=g:moduleRtn=new Promise((a,b)=>{fa=a;ha=b});
;return moduleRtn}export default Module;
