async function Module(moduleArg={}){var moduleRtn;var m=moduleArg;if(globalThis.process?.versions?.node&&globalThis.process?.type!="renderer"){var fs=require("node:fs");m.wasm=fs.readFileSync(__dirname+"/webp_module.wasm")}var p,t=!1;function u(){var a=w.buffer;x=new Int8Array(a);y=new Int16Array(a);z=new Uint8Array(a);A=new Uint16Array(a);D=new Int32Array(a);E=new Uint32Array(a);F=new Float32Array(a);G=new Float64Array(a);aa=new BigInt64Array(a);ba=new BigUint64Array(a)}
var y,D,aa,x,F,G,A,E,ba,z,ca=new TextDecoder,da=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},J=(a,b,c)=>a?ca.decode(z.subarray(a,da(z,a,b,c))):"";class ea{constructor(a){this.M=a-24}init(a,b){E[this.M+16>>2]=0;E[this.M+4>>2]=a;E[this.M+8>>2]=b}}var fa=0,K=a=>{for(var b="";;){var c=z[a++];if(!c)return b;b+=String.fromCharCode(c)}},L={},M={},N={},O=class extends Error{constructor(a){super(a);this.name="BindingError"}},ha=a=>{throw new O(a);};
function ia(a,b,c={}){var d=b.name;if(!a)throw new O(`type "${d}" must have a positive integer typeid pointer`);if(M.hasOwnProperty(a)){if(c.P)return;throw new O(`Cannot register type '${d}' twice`);}M[a]=b;delete N[a];L.hasOwnProperty(a)&&(b=L[a],delete L[a],b.forEach(e=>e()))}function P(a,b,c={}){return ia(a,b,c)}
var ja=(a,b,c)=>{switch(b){case 1:return c?d=>x[d]:d=>z[d];case 2:return c?d=>y[d>>1]:d=>A[d>>1];case 4:return c?d=>D[d>>2]:d=>E[d>>2];case 8:return c?d=>aa[d>>3]:d=>ba[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},ka=[],Q=[0,1,,1,null,1,!0,1,!1,1],R=a=>{a>9&&0===--Q[a+1]&&(Q[a]=void 0,ka.push(a))},S=a=>{if(!a)throw new O(`Cannot use deleted val. handle = ${a}`);return Q[a]},T=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:let b=
ka.pop()||Q.length;Q[b]=a;Q[b+1]=1;return b}};function V(a){return this.H(E[a>>2])}var la={name:"emscripten::val",H:a=>{var b=S(a);R(a);return b},K:(a,b)=>T(b),L:V,J:null},ma=(a,b)=>{switch(b){case 4:return function(c){return this.H(F[c>>2])};case 8:return function(c){return this.H(G[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},na=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function ra(a){for(var b=1;b<a.length;++b)if(a[b]!==null&&a[b].J===void 0)return!0;return!1}
var sa=(a,b)=>{if(void 0===m[a].I){var c=m[a];m[a]=function(...d){if(!m[a].I.hasOwnProperty(d.length))throw new O(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${m[a].I})!`);return m[a].I[d.length].apply(this,d)};m[a].I=[];m[a].I[c.N]=c}},ta=(a,b,c)=>{if(m.hasOwnProperty(a)){if(void 0===c||void 0!==m[a].I&&void 0!==m[a].I[c])throw new O(`Cannot register public name '${a}' twice`);sa(a,a);if(m[a].I.hasOwnProperty(c))throw new O(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
m[a].I[c]=b}else m[a]=b,m[a].N=c},ua=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(E[b+d*4>>2]);return c},va=class extends Error{constructor(a){super(a);this.name="InternalError"}},xa=(a,b)=>{a=K(a);var c=wa.get(b);if(typeof c!="function")throw new O(`unknown function pointer with signature ${a}: ${b}`);return c};class ya extends Error{}
var Aa=a=>{a=za(a);var b=K(a);W(a);return b},Ba=(a,b)=>{function c(f){e[f]||M[f]||(N[f]?N[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new ya(`${a}: `+d.map(Aa).join([", "]));},Ca=(a,b)=>{function c(g){g=b(g);if(g.length!==d.length)throw new va("Mismatched type converter count");for(var l=0;l<d.length;++l)P(d[l],g[l])}var d=[];d.forEach(g=>N[g]=a);var e=Array(a.length),f=[],h=0;for(let [g,l]of a.entries())M.hasOwnProperty(l)?e[g]=M[l]:(f.push(l),L.hasOwnProperty(l)||(L[l]=[]),
L[l].push(()=>{e[g]=M[l];++h;h===f.length&&c(e)}));0===f.length&&c(e)},Da=a=>{a=a.trim();var b=a.indexOf("(");return b===-1?a:a.slice(0,b)},Ea=new TextDecoder("utf-16le"),Fa=(a,b,c)=>{a>>=1;return Ea.decode(A.subarray(a,da(A,a,b/2,c)))},Ga=(a,b,c)=>{c??=2147483647;if(c<2)return 0;c-=2;var d=b;c=c<a.length*2?c/2:a.length;for(var e=0;e<c;++e)y[b>>1]=a.charCodeAt(e),b+=2;y[b>>1]=0;return b-d},Ha=a=>a.length*2,Ia=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=E[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},
Ja=(a,b,c)=>{c??=2147483647;if(c<4)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);f>65535&&e++;D[b>>2]=f;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d},Ka=a=>{for(var b=0,c=0;c<a.length;++c)a.codePointAt(c)>65535&&c++,b+=4;return b},X=[],La=a=>{var b=X.length;X.push(a);return b},Ma=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=E[b+d*4>>2],h=M[f];if(void 0===h)throw a=`${`parameter ${d}`} has unknown type ${Aa(f)}`,new O(a);c[e]=h}return c},Na=(a,b,c)=>{var d=[];a=a(d,c);
d.length&&(E[b>>2]=T(d));return a},Oa={},Pa=a=>{var b=Oa[a];return b===void 0?K(a):b},Y={},Z,W,za,Qa,w,wa;
WebAssembly.instantiate(m.wasm,{a:{a:(a,b,c,d)=>{throw`Assertion failed: ${J(a)}, at: `+[b?J(b):"unknown filename",c,d?J(d):"unknown function"];},q:(a,b,c)=>{(new ea(a)).init(b,c);fa++;throw void 0;},v:()=>{throw"";},o:(a,b,c,d,e)=>{b=K(b);d=d===0n;var f=h=>h;if(d){let h=c*8;f=g=>BigInt.asUintN(h,g);e=f(e)}P(a,{name:b,H:f,K:(h,g)=>{typeof g=="number"&&(g=BigInt(g));return g},L:ja(b,c,!d),J:null})},y:(a,b,c,d)=>{b=K(b);P(a,{name:b,H:function(e){return!!e},K:function(e,f){return f?c:d},L:function(e){return this.H(z[e])},
J:null})},w:a=>P(a,la),n:(a,b,c)=>{b=K(b);P(a,{name:b,H:d=>d,K:(d,e)=>e,L:ma(b,c),J:null})},e:(a,b,c,d,e,f,h)=>{var g=ua(b,c);a=K(a);a=Da(a);e=xa(d,e);ta(a,function(){Ba(`Cannot call ${a} due to unbound types`,g)},b-1);Ca(g,l=>{var k=[l[0],null].concat(l.slice(1));l=a;var B=a;var H=e,n=k.length;if(n<2)throw new O("argTypes array size mismatch! Must at least get return value and 'this' types!");var C=k[1]!==null&&!1,I=ra(k),oa=!k[0].O,q=k[0],v=k[1];H=[B,ha,H,f,na,q.H.bind(q),v?.K.bind(v)];for(q=2;q<
n;++q)v=k[q],H.push(v.K.bind(v));if(!I)for(q=C?1:2;q<k.length;++q)k[q].J!==null&&H.push(k[q].J);I=ra(k);q=k.length-2;var r=[];v=["fn"];C&&v.push("thisWired");for(n=0;n<q;++n)r.push(`arg${n}`),v.push(`arg${n}Wired`);r=r.join(",");v=v.join(",");r=`return function (${r}) {\n`;I&&(r+="var destructors = [];\n");var pa=I?"destructors":"null",U="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");C&&(r+=`var thisWired = toClassParamWire(${pa}, this);\n`);for(n=
0;n<q;++n){var qa=`toArg${n}Wire`;r+=`var arg${n}Wired = ${qa}(${pa}, arg${n});\n`;U.push(qa)}r+=(oa||h?"var rv = ":"")+`invoker(${v});\n`;if(I)r+="runDestructors(destructors);\n";else for(n=C?1:2;n<k.length;++n)C=n===1?"thisWired":"arg"+(n-2)+"Wired",k[n].J!==null&&(r+=`${C}_dtor(${C});\n`,U.push(`${C}_dtor`));oa&&(r+="var ret = fromRetWire(rv);\nreturn ret;\n");k=(new Function(U,r+"}\n"))(...H);B=Object.defineProperty(k,"name",{value:B});k=b-1;if(!m.hasOwnProperty(l))throw new va("Replacing nonexistent public symbol");
void 0!==m[l].I&&void 0!==k?m[l].I[k]=B:(m[l]=B,m[l].N=k);return[]})},d:(a,b,c,d,e)=>{b=K(b);var f=g=>g;if(d===0){var h=32-8*c;f=g=>g<<h>>>h;e=f(e)}P(a,{name:b,H:f,K:(g,l)=>l,L:ja(b,c,d!==0),J:null})},b:(a,b,c)=>{function d(f){return new e(x.buffer,E[f+4>>2],E[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=K(c);P(a,{name:c,H:d,L:d},{P:!0})},x:(a,b)=>{b=K(b);P(a,{name:b,H(c){var d=J(c+4,E[c>>2],!0);W(c);
return d},K(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,f=typeof d=="string";if(!(f||ArrayBuffer.isView(d)&&d.BYTES_PER_ELEMENT==1))throw new O("Cannot pass non-string to std::string");var h;if(f)for(e=h=0;e<d.length;++e){var g=d.charCodeAt(e);g<=127?h++:g<=2047?h+=2:g>=55296&&g<=57343?(h+=4,++e):h+=3}else h=d.length;e=h;h=Z(4+e+1);g=h+4;E[h>>2]=e;if(f){if(f=g,g=e+1,e=z,g>0){g=f+g-1;for(var l=0;l<d.length;++l){var k=d.codePointAt(l);if(k<=127){if(f>=g)break;e[f++]=k}else if(k<=2047){if(f+
1>=g)break;e[f++]=192|k>>6;e[f++]=128|k&63}else if(k<=65535){if(f+2>=g)break;e[f++]=224|k>>12;e[f++]=128|k>>6&63;e[f++]=128|k&63}else{if(f+3>=g)break;e[f++]=240|k>>18;e[f++]=128|k>>12&63;e[f++]=128|k>>6&63;e[f++]=128|k&63;l++}}e[f]=0}}else z.set(d,g);c!==null&&c.push(W,h);return h},L:V,J(c){W(c)}})},k:(a,b,c)=>{c=K(c);if(b===2){var d=Fa;var e=Ga;var f=Ha}else d=Ia,e=Ja,f=Ka;P(a,{name:c,H:h=>{var g=d(h+4,E[h>>2]*b,!0);W(h);return g},K:(h,g)=>{if(typeof g!="string")throw new O(`Cannot pass non-string to C++ string type ${c}`);
var l=f(g),k=Z(4+l+b);E[k>>2]=l/b;e(g,k+4,l+b);h!==null&&h.push(W,k);return k},L:V,J(h){W(h)}})},z:(a,b)=>{b=K(b);P(a,{O:!0,name:b,H:()=>{},K:()=>{}})},u:()=>{},h:(a,b,c)=>{var d;[b,...d]=Ma(a,b);var e=b.K.bind(b),f=d.map(l=>l.L.bind(l));a--;var h={toValue:S};a=f.map((l,k)=>{var B=`argFromPtr${k}`;h[B]=l;return`${B}(args${k?"+"+k*8:""})`});switch(c){case 0:var g="toValue(handle)";break;case 2:g="new (toValue(handle))";break;case 3:g="";break;case 1:h.getStringOrSymbol=Pa,g="toValue(handle)[getStringOrSymbol(methodName)]"}g+=
`(${a})`;b.O||(h.toReturnWire=e,h.emval_returnValue=Na,g=`return emval_returnValue(toReturnWire, destructorsRef, ${g})`);g=`return function (handle, methodName, destructorsRef, args) {\n${g}\n}`;c=(new Function(Object.keys(h),g))(...Object.values(h));b=`methodCaller<(${d.map(l=>l.name)}) => ${b.name}>`;return La(Object.defineProperty(c,"name",{value:b}))},c:R,m:(a,b)=>{a=S(a);b=S(b);return T(a[b])},j:a=>{a>9&&(Q[a+1]+=1)},g:(a,b,c,d,e)=>X[a](b,c,d,e),i:a=>T(Pa(a)),p:()=>T({}),f:a=>{var b=S(a);na(b);
R(a)},l:(a,b,c)=>{a=S(a);b=S(b);c=S(c);a[b]=c},r:(a,b)=>{Y[a]&&(clearTimeout(Y[a].id),delete Y[a]);if(!b)return 0;var c=setTimeout(()=>{delete Y[a];Qa(a,performance.now())},b);Y[a]={id:c,R:b};return 0},s:a=>{var b=z.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-w.buffer.byteLength+65535)/65536|0;try{w.grow(d);u();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},t:a=>
{throw`exit(${a})`;}}}).then(a=>{a=a.instance.exports;Z=a.D;W=a.E;za=a.F;Qa=a.G;w=a.A;wa=a.C;u();t=!0;a.B();p?.(m)});t?moduleRtn=m:moduleRtn=new Promise(a=>{p=a});
;return moduleRtn}export default Module;
